# Generated by Django 5.2.13 on 2026-04-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_master_student_remove_post_category_mentor_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['title'], 'verbose_name': 'Guruh', 'verbose_name_plural': 'Guruhlar'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['subject'], 'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar'},
        ),
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ['firstname'], 'verbose_name': 'Mentor', 'verbose_name_plural': 'Mentorlar'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['firstname'], 'verbose_name': "O'quvchi", 'verbose_name_plural': "O'quvchilar"},
        ),
    ]
